// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgJh2Qvx2wfXZLnfSA1KJ861Rwf17rIHI',
    appId: '1:315476876936:web:6c8b70aa7de2c542e2493d',
    messagingSenderId: '315476876936',
    projectId: 'socialcircle-e9a40',
    authDomain: 'socialcircle-e9a40.firebaseapp.com',
    storageBucket: 'socialcircle-e9a40.appspot.com',
    measurementId: 'G-K5EVT1S93T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIwVTYTx4Fht9f3dnCGfAcHej-IAo4Iyg',
    appId: '1:315476876936:android:7124619561a5a78ce2493d',
    messagingSenderId: '315476876936',
    projectId: 'socialcircle-e9a40',
    storageBucket: 'socialcircle-e9a40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlpIc3JA9_VQNxZ-ZlgP77Z9RViiQ4joc',
    appId: '1:315476876936:ios:d89f180e867a9b8de2493d',
    messagingSenderId: '315476876936',
    projectId: 'socialcircle-e9a40',
    storageBucket: 'socialcircle-e9a40.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlpIc3JA9_VQNxZ-ZlgP77Z9RViiQ4joc',
    appId: '1:315476876936:ios:d89f180e867a9b8de2493d',
    messagingSenderId: '315476876936',
    projectId: 'socialcircle-e9a40',
    storageBucket: 'socialcircle-e9a40.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgJh2Qvx2wfXZLnfSA1KJ861Rwf17rIHI',
    appId: '1:315476876936:web:0ce0207c2f2d462ae2493d',
    messagingSenderId: '315476876936',
    projectId: 'socialcircle-e9a40',
    authDomain: 'socialcircle-e9a40.firebaseapp.com',
    storageBucket: 'socialcircle-e9a40.appspot.com',
    measurementId: 'G-2Z1SZZQGXQ',
  );
}
